apiVersion: v1
kind: Service
metadata:
  name: gestiondestock-api
  namespace: gestionstock
spec:
  selector:
    app: gestiondestock-api
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
