apiVersion: v1
kind: Service
metadata:
  name: gestiondestock-ui
  namespace: gestionstock
spec:
  selector:
    app: gestiondestock-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
