spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/gestion?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Med123456*
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false


    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081
application:
  cors: http://192.168.0.227:8081/,http://localhost:8081/,http://localhost:4200,http://192.168.0.227:8080

flickr:
  apiKey: ad851f14021ee3cf1af27ecbee9a5121
  apiSecret: de016b82cf892963
  appKey: 72157720909135357-2b889b899a11e841
  appSecret: 4c2f916b29a40040

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      enable:
        process: true  
  server:
    port: 8081

