name: gestion-stock Frontend Pipeline

on:
  push:
    branches:
      - master
    paths:
      - gestion_stock_ui/hb_electronics/**
      - Docker/frontend/**
      - "docker-compose.yml"
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: Build FE Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract project version
        id: extract_version
        run: |
          cd gestion_stock_ui/hb_electronics
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: gestion_stock_ui/hb_electronics
          file: Docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gestiondestock-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gestiondestock-ui:${{ steps.extract_version.outputs.VERSION }}

#Intégrer SonarQube dans un pipeline frontend, c’est comme mettre un contrôle technique automatique sur ton code à chaque push. Ça te protège contre les erreurs subtiles, améliore la lisibilité, et augmente la fiabilité de ton application.
#deploy:
# name: Deploy Frontend to Kubernetes
# runs-on: ubuntu-latest
# needs: [ build-image ]
# steps:
#  - name: Set K8s context
#    uses: azure/k8s-set-context@v3
#    with:
#      method: kubeconfig
#      kubeconfig: ${{ secrets.KUBE_CONFIG }}

#  - name: Deploy to Kubernetes
#    run: |
#      kubectl set image deployment/gestiondestock-ui gestiondestock-ui=${{ secrets.DOCKERHUB_USERNAME }}/gestiondestock-ui:${{ steps.extract_version.outputs.VERSION }} -n gestionstock
#      kubectl rollout restart deployment/gestiondestock-ui -n gestionstock
